#include<iostream>
#include<ctime>
#include<cstdlib>
using namespace std;
int main()
{
     srand(time(0));

     int random_number = (rand()%100)+1;
     cout<<"_____ Welcome to the game____" <<endl ;
     //cout<< "This is the random number generated by the computer :" << random_number <<endl;

     cout<< "_____Guess the number from 1 to 100!_____" <<endl;
     cout<< "   "<<endl;
     cout<< "   "<<endl;
     cout<< "   "<<endl;
     cout<< "   "<<endl;
     
     //cin>> guess_number ;
     int guess_number = 0;

     while(guess_number != random_number)
     {  cin>> guess_number ;
          if (guess_number == random_number)
          {
               cout<< "Congratulation!  You Did it " << endl;

               return 0;
          }

          else if (guess_number < random_number)
          {
           cout << " You are cold ! " <<endl;
           cout << " Try again " <<endl;
            continue ;
          }
          else
          {
           cout << " You are Hot!" <<endl;
           cout << " You are cold ! " <<endl;
            continue ;
          }
          continue ;
     }


}
